import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 1. Load data
df = pd.read_csv('sample.csv', index_col=0)

# Ensure the index is converted to datetime for proper calendar features extraction
df.index = pd.to_datetime(df.index)

columns_list = ['Pay_Type_1', 'Pay_Type_2', 'Total_Payment']
results_list = []
forecasts_xgb_dict = {}
forecasts_rf_dict = {}

# Number of historical days the models will use to predict the next step
LAG_DAYS = 7 

for i in columns_list:
    # Create a copy of the dataframe for the current column to prevent Data-Leakage or view warnings
    df_features = pd.DataFrame(df[i].copy())
    
    # Generate lag features (historical values for the last 7 days)
    for lag in range(1, LAG_DAYS + 1):
        df_features[f'lag_{lag}'] = df_features[i].shift(lag)
        
    # Calculate rolling window features (calculated inside the column loop)
    # Using shift(1) avoids data leakage by looking strictly at historical windows
    df_features['rolling_mean_3'] = df_features[i].shift(1).rolling(3).mean()
    df_features['rolling_mean_7'] = df_features[i].shift(1).rolling(7).mean()
    df_features['rolling_std_7'] = df_features[i].shift(1).rolling(7).std()
        
    # Generate calendar features (critical for capturing business cycles and payment patterns)
    df_features['day_of_week'] = df_features.index.dayofweek
    df_features['day_of_month'] = df_features.index.day
    
    # Drop rows containing NaN values generated by lag and rolling window transformations
    df_features = df_features.dropna()
    
    # Split the dataset into features (X) and target variable (y)
    X = df_features.drop(columns=[i])
    y = df_features[i]
    
    # Perform time-series sequential split into Train and Test sets (80 / 20)
    split_idx = int(len(df_features) * 0.8)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]
    
    # --- MODEL 1: XGBoost ---
    model_xgb = XGBRegressor(n_estimators=100, max_depth=5, learning_rate=0.05, random_state=42)
    model_xgb.fit(X_train, y_train)
    preds_xgb = model_xgb.predict(X_test)
    forecasts_xgb_dict[i] = preds_xgb[:7]
    
    # Calculate performance metrics for XGBoost
    mae_xgb = mean_absolute_error(preds_xgb, y_test)
    rmse_xgb = mean_squared_error(preds_xgb, y_test)**0.5
    results_list.append({'Model': 'XGBoost', 'set': i, 'MAE': mae_xgb, 'RMSE': rmse_xgb})
    
    # --- MODEL 2: Random Forest ---
    # n_estimators=100 (number of trees), max_depth=8 (deeper trees are typical for RF compared to boosting)
    # n_jobs=-1 utilizes all available CPU cores for parallel training
    model_rf = RandomForestRegressor(n_estimators=100, max_depth=8, random_state=42, n_jobs=-1)
    model_rf.fit(X_train, y_train)
    preds_rf = model_rf.predict(X_test)
    forecasts_rf_dict[i] = preds_rf[:7]
    
    # Calculate performance metrics for Random Forest
    mae_rf = mean_absolute_error(preds_rf, y_test)
    rmse_rf = mean_squared_error(preds_rf, y_test)**0.5
    results_list.append({'Model': 'Random Forest', 'set': i, 'MAE': mae_rf, 'RMSE': rmse_rf})

# 2. Display comparison metrics table
df_metrics = pd.DataFrame(results_list)
print("--- COMPARISON METRICS ---")
# Sorted by target subset and RMSE to easily identify the best-performing model
print(df_metrics.sort_values(by=['set', 'RMSE'])) 
print("\n" + "="*50 + "\n")

# 3. Create and display final forecast DataFrames for the first 7 test steps
forecast_index = [f"Step +{k}" for k in range(1, 8)]
df_future_xgb = pd.DataFrame(forecasts_xgb_dict, index=forecast_index)
df_future_rf = pd.DataFrame(forecasts_rf_dict, index=forecast_index)

print("--- XGBoost Forecast (First 7 steps) ---")
print(df_future_xgb)
print("\n--- Random Forest Forecast (First 7 steps) ---")
print(df_future_rf)